Repository PrusinowskyPrime/Timesheet-Kotlin, pull requests merged in 2023-11, with the labels that each got.

#4 TK-002: Projects module
  compose.yaml
  src/main/kotlin/pl/prusinowsky/timesheet/project/controller/ProjectController.kt
  src/main/kotlin/pl/prusinowsky/timesheet/project/entity/ProjectEntity.kt
  src/main/kotlin/pl/prusinowsky/timesheet/project/model/ProjectCreate.kt
  src/main/kotlin/pl/prusinowsky/timesheet/project/model/ProjectResponse.kt
  src/main/kotlin/pl/prusinowsky/timesheet/project/model/ProjectUpdate.kt
  src/main/kotlin/pl/prusinowsky/timesheet/project/repository/ProjectRepository.kt
  src/main/kotlin/pl/prusinowsky/timesheet/project/service/ProjectService.kt
Labels: draft

#8 TK-004: Work module
  src/main/kotlin/pl/prusinowsky/timesheet/work/controller/WorkController.kt
  src/main/kotlin/pl/prusinowsky/timesheet/work/entity/WorkEntity.kt
  src/main/kotlin/pl/prusinowsky/timesheet/work/model/CreateWork.kt
  src/main/kotlin/pl/prusinowsky/timesheet/work/model/UpdateWork.kt
  src/main/kotlin/pl/prusinowsky/timesheet/work/model/WorkResponse.kt
  src/main/kotlin/pl/prusinowsky/timesheet/work/repository/WorkRepository.kt
  src/main/kotlin/pl/prusinowsky/timesheet/work/service/WorkService.kt
Labels: enhancement

#9 TK-003: Task module
  src/main/kotlin/pl/prusinowsky/timesheet/task/controller/TaskController.kt
  src/main/kotlin/pl/prusinowsky/timesheet/task/entity/TaskEntity.kt
  src/main/kotlin/pl/prusinowsky/timesheet/task/model/CreateTask.kt
  src/main/kotlin/pl/prusinowsky/timesheet/task/model/TaskResponse.kt
  src/main/kotlin/pl/prusinowsky/timesheet/task/model/UpdateTask.kt
  src/main/kotlin/pl/prusinowsky/timesheet/task/repository/TaskRepository.kt
  src/main/kotlin/pl/prusinowsky/timesheet/task/service/TaskService.kt
Labels: enhancement

#15 TK-001: Refactor UserService method names and declarations
  src/main/kotlin/pl/prusinowsky/timesheet/user/controller/UserController.kt
  src/main/kotlin/pl/prusinowsky/timesheet/user/service/UserService.kt
Labels: refactor

#16 TK-002: Refactor ProjectService method names and declarations
  src/main/kotlin/pl/prusinowsky/timesheet/project/controller/ProjectController.kt
  src/main/kotlin/pl/prusinowsky/timesheet/project/service/ProjectService.kt
Labels: refactor
